const nodes = [
  {
    id: "1",
    title: "Book 1",
    author: {
      id: "1",
      fullName: "Author 1",
      birthday: "1990-01-01",
    },
    isAvailable: true,
    note: "Note 1",
    createdDate: "2024-04-09",
    isbn: "ISBN-1",
    genre: "HORROR",
  },
  {
    id: "2",
    title: "Book 2",
    author: {
      id: "2",
      fullName: "Author 2",
      birthday: "1985-05-15",
    },
    isAvailable: true,
    note: "Note 2",
    createdDate: "2024-04-09",
    isbn: "ISBN-2",
    genre: "THRILLER",
  },
  {
    id: "3",
    title: "Book 3",
    author: {
      id: "3",
      fullName: "Author 3",
      birthday: "1978-11-20",
    },
    isAvailable: false,
    note: "Note 3",
    createdDate: "2024-04-09",
    isbn: "ISBN-3",
    genre: "COMEDY",
  },
  {
    id: "4",
    title: "Book 4",
    author: {
      id: "4",
      fullName: "Author 4",
      birthday: "1982-03-10",
    },
    isAvailable: true,
    note: "Note 4",
    createdDate: "2024-04-09",
    isbn: "ISBN-4",
    genre: "ROMANCE",
  },
  {
    id: "5",
    title: "Book 5",
    author: {
      id: "5",
      fullName: "Author 5",
      birthday: "1995-08-28",
    },
    isAvailable: false,
    note: "Note 5",
    createdDate: "2024-04-09",
    isbn: "ISBN-5",
    genre: "DRAMA",
  },
  {
    id: "6",
    title: "Book 6",
    author: {
      id: "6",
      fullName: "Author 6",
      birthday: "1987-02-14",
    },
    isAvailable: true,
    note: "Note 6",
    createdDate: "2024-04-09",
    isbn: "ISBN-6",
    genre: "HORROR",
  },
  {
    id: "7",
    title: "Book 7",
    author: {
      id: "7",
      fullName: "Author 7",
      birthday: "1992-06-30",
    },
    isAvailable: false,
    note: "Note 7",
    createdDate: "2024-04-09",
    isbn: "ISBN-7",
    genre: "THRILLER",
  },
  {
    id: "8",
    title: "Book 8",
    author: {
      id: "8",
      fullName: "Author 8",
      birthday: "1980-09-05",
    },
    isAvailable: true,
    note: "Note 8",
    createdDate: "2024-04-09",
    isbn: "ISBN-8",
    genre: "COMEDY",
  },
  {
    id: "9",
    title: "Book 9",
    author: {
      id: "9",
      fullName: "Author 9",
      birthday: "1976-12-25",
    },
    isAvailable: false,
    note: "Note 9",
    createdDate: "2024-04-09",
    isbn: "ISBN-9",
    genre: "ROMANCE",
  },
  {
    id: "10",
    title: "Book 10",
    author: {
      id: "10",
      fullName: "Author 10",
      birthday: "1988-04-03",
    },
    isAvailable: true,
    note: "Note 10",
    createdDate: "2024-04-09",
    isbn: "ISBN-10",
    genre: "DRAMA",
  },  {
    id: "11",
    title: "Book 1",
    author: {
      id: "1",
      fullName: "Author 1",
      birthday: "1990-01-01",
    },
    isAvailable: true,
    note: "Note 1",
    createdDate: "2024-04-09",
    isbn: "ISBN-1",
    genre: "HORROR",
  },
  {
    id: "21",
    title: "Book 2",
    author: {
      id: "2",
      fullName: "Author 2",
      birthday: "1985-05-15",
    },
    isAvailable: true,
    note: "Note 2",
    createdDate: "2024-04-09",
    isbn: "ISBN-2",
    genre: "THRILLER",
  },
  {
    id: "31",
    title: "Book 3",
    author: {
      id: "3",
      fullName: "Author 3",
      birthday: "1978-11-20",
    },
    isAvailable: false,
    note: "Note 3",
    createdDate: "2024-04-09",
    isbn: "ISBN-3",
    genre: "COMEDY",
  },
  {
    id: "41",
    title: "Book 4",
    author: {
      id: "4",
      fullName: "Author 4",
      birthday: "1982-03-10",
    },
    isAvailable: true,
    note: "Note 4",
    createdDate: "2024-04-09",
    isbn: "ISBN-4",
    genre: "ROMANCE",
  },
  {
    id: "51",
    title: "Book 5",
    author: {
      id: "5",
      fullName: "Author 5",
      birthday: "1995-08-28",
    },
    isAvailable: false,
    note: "Note 5",
    createdDate: "2024-04-09",
    isbn: "ISBN-5",
    genre: "DRAMA",
  },
  {
    id: "61",
    title: "Book 6",
    author: {
      id: "6",
      fullName: "Author 6",
      birthday: "1987-02-14",
    },
    isAvailable: true,
    note: "Note 6",
    createdDate: "2024-04-09",
    isbn: "ISBN-6",
    genre: "HORROR",
  },
  {
    id: "71",
    title: "Book 7",
    author: {
      id: "7",
      fullName: "Author 7",
      birthday: "1992-06-30",
    },
    isAvailable: false,
    note: "Note 7",
    createdDate: "2024-04-09",
    isbn: "ISBN-7",
    genre: "THRILLER",
  },
  {
    id: "81",
    title: "Book 8",
    author: {
      id: "8",
      fullName: "Author 8",
      birthday: "1980-09-05",
    },
    isAvailable: true,
    note: "Note 8",
    createdDate: "2024-04-09",
    isbn: "ISBN-8",
    genre: "COMEDY",
  },
  {
    id: "91",
    title: "Book 9",
    author: {
      id: "9",
      fullName: "Author 9",
      birthday: "1976-12-25",
    },
    isAvailable: false,
    note: "Note 9",
    createdDate: "2024-04-09",
    isbn: "ISBN-9",
    genre: "ROMANCE",
  },
  {
    id: "101",
    title: "Book 10",
    author: {
      id: "10",
      fullName: "Author 10",
      birthday: "1988-04-03",
    },
    isAvailable: true,
    note: "Note 10",
    createdDate: "2024-04-09",
    isbn: "ISBN-10",
    genre: "DRAMA",
  },
];


export default nodes;