frontend:
    url: ${FRONTEND_URL}
rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
spring:
    datasource:
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://${DB_URL}
        username: ${DB_NAME}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_ID}
                        client-secret: ${GITHUB_SECRET}
                    google:
                        client-id: ${GOOGLE_ID}
                        client-secret: ${GOOGLE_SECRET}
        user:
            password: ${SECURITY_PASS}
management:
    endpoints:
        web:
            exposure:
                include: auditevents, beans, conditions, configprops, env, flyway, health, heapdump, info, liquibase, logfile, loggers, metrics, prometheus, scheduledtasks, sessions, shutdown, threaddump
springdoc:
    api-docs:
        path: /api-docs

